/**
 * Raven61 physical layout: ANSI 60 %, 61 keys, 15u x 5u.
 *
 * GENERATED by tools/layout/from-vendor-xml.mjs from the stock driver's
 * layouts/Raven61.xml — do not hand-edit; re-run the generator instead.
 *
 * - `index`     this file's ordering (row-major, left to right); what the UI uses.
 * - `keyIndex`  the FIRMWARE's key address, used in every protocol command.
 *               It is not contiguous and does not follow the visual order:
 *               Backspace is 92, Enter 76, Menu 109.
 * - `lightIndex` per-key LED address. Mostly equal to keyIndex; the vendor XML
 *               lists 37 for both "-" and "T", which looks like their bug.
 */
export interface KeyDef {
  index: number
  label: string
  /** Default HID Keyboard/Keypad (page 0x07) usage id. 0xff = Fn, no HID code. */
  code: number
  /** Position in keyboard units from the top-left. */
  x: number
  y: number
  w: number
  /** Firmware key address — the value the board expects in commands. */
  keyIndex: number
  /** Per-key LED address. */
  lightIndex: number
}

export const RAVEN61_KEYS: KeyDef[] = [
  { index: 0, label: "Esc", code: 0x29, x: 0, y: 0, w: 1, keyIndex: 16, lightIndex: 16 },
  { index: 1, label: "1", code: 0x1e, x: 1, y: 0, w: 1, keyIndex: 17, lightIndex: 17 },
  { index: 2, label: "2", code: 0x1f, x: 2, y: 0, w: 1, keyIndex: 18, lightIndex: 18 },
  { index: 3, label: "3", code: 0x20, x: 3, y: 0, w: 1, keyIndex: 19, lightIndex: 19 },
  { index: 4, label: "4", code: 0x21, x: 4, y: 0, w: 1, keyIndex: 20, lightIndex: 20 },
  { index: 5, label: "5", code: 0x22, x: 5, y: 0, w: 1, keyIndex: 21, lightIndex: 21 },
  { index: 6, label: "6", code: 0x23, x: 6, y: 0, w: 1, keyIndex: 22, lightIndex: 22 },
  { index: 7, label: "7", code: 0x24, x: 7, y: 0, w: 1, keyIndex: 23, lightIndex: 23 },
  { index: 8, label: "8", code: 0x25, x: 8, y: 0, w: 1, keyIndex: 24, lightIndex: 24 },
  { index: 9, label: "9", code: 0x26, x: 9, y: 0, w: 1, keyIndex: 25, lightIndex: 25 },
  { index: 10, label: "0", code: 0x27, x: 10, y: 0, w: 1, keyIndex: 26, lightIndex: 26 },
  { index: 11, label: "-", code: 0x2d, x: 11, y: 0, w: 1, keyIndex: 27, lightIndex: 37 },
  { index: 12, label: "=", code: 0x2e, x: 12, y: 0, w: 1, keyIndex: 28, lightIndex: 28 },
  { index: 13, label: "Backspace", code: 0x2a, x: 13, y: 0, w: 2, keyIndex: 92, lightIndex: 92 },
  { index: 14, label: "Tab", code: 0x2b, x: 0, y: 1, w: 1.5, keyIndex: 32, lightIndex: 32 },
  { index: 15, label: "Q", code: 0x14, x: 1.5, y: 1, w: 1, keyIndex: 33, lightIndex: 33 },
  { index: 16, label: "W", code: 0x1a, x: 2.5, y: 1, w: 1, keyIndex: 34, lightIndex: 34 },
  { index: 17, label: "E", code: 0x08, x: 3.5, y: 1, w: 1, keyIndex: 35, lightIndex: 35 },
  { index: 18, label: "R", code: 0x15, x: 4.5, y: 1, w: 1, keyIndex: 36, lightIndex: 36 },
  { index: 19, label: "T", code: 0x17, x: 5.5, y: 1, w: 1, keyIndex: 37, lightIndex: 37 },
  { index: 20, label: "Y", code: 0x1c, x: 6.5, y: 1, w: 1, keyIndex: 38, lightIndex: 38 },
  { index: 21, label: "U", code: 0x18, x: 7.5, y: 1, w: 1, keyIndex: 39, lightIndex: 39 },
  { index: 22, label: "I", code: 0x0c, x: 8.5, y: 1, w: 1, keyIndex: 40, lightIndex: 40 },
  { index: 23, label: "O", code: 0x12, x: 9.5, y: 1, w: 1, keyIndex: 41, lightIndex: 41 },
  { index: 24, label: "P", code: 0x13, x: 10.5, y: 1, w: 1, keyIndex: 42, lightIndex: 42 },
  { index: 25, label: "[", code: 0x2f, x: 11.5, y: 1, w: 1, keyIndex: 43, lightIndex: 43 },
  { index: 26, label: "]", code: 0x30, x: 12.5, y: 1, w: 1, keyIndex: 44, lightIndex: 44 },
  { index: 27, label: "\\", code: 0x31, x: 13.5, y: 1, w: 1.5, keyIndex: 60, lightIndex: 60 },
  { index: 28, label: "Caps", code: 0x39, x: 0, y: 2, w: 1.75, keyIndex: 48, lightIndex: 48 },
  { index: 29, label: "A", code: 0x04, x: 1.75, y: 2, w: 1, keyIndex: 49, lightIndex: 49 },
  { index: 30, label: "S", code: 0x16, x: 2.75, y: 2, w: 1, keyIndex: 50, lightIndex: 50 },
  { index: 31, label: "D", code: 0x07, x: 3.75, y: 2, w: 1, keyIndex: 51, lightIndex: 51 },
  { index: 32, label: "F", code: 0x09, x: 4.75, y: 2, w: 1, keyIndex: 52, lightIndex: 52 },
  { index: 33, label: "G", code: 0x0a, x: 5.75, y: 2, w: 1, keyIndex: 53, lightIndex: 53 },
  { index: 34, label: "H", code: 0x0b, x: 6.75, y: 2, w: 1, keyIndex: 54, lightIndex: 54 },
  { index: 35, label: "J", code: 0x0d, x: 7.75, y: 2, w: 1, keyIndex: 55, lightIndex: 55 },
  { index: 36, label: "K", code: 0x0e, x: 8.75, y: 2, w: 1, keyIndex: 56, lightIndex: 56 },
  { index: 37, label: "L", code: 0x0f, x: 9.75, y: 2, w: 1, keyIndex: 57, lightIndex: 57 },
  { index: 38, label: ";", code: 0x33, x: 10.75, y: 2, w: 1, keyIndex: 58, lightIndex: 58 },
  { index: 39, label: "'", code: 0x34, x: 11.75, y: 2, w: 1, keyIndex: 59, lightIndex: 59 },
  { index: 40, label: "Enter", code: 0x28, x: 12.75, y: 2, w: 2.25, keyIndex: 76, lightIndex: 76 },
  { index: 41, label: "Shift", code: 0xe1, x: 0, y: 3, w: 2.25, keyIndex: 64, lightIndex: 64 },
  { index: 42, label: "Z", code: 0x1d, x: 2.25, y: 3, w: 1, keyIndex: 65, lightIndex: 65 },
  { index: 43, label: "X", code: 0x1b, x: 3.25, y: 3, w: 1, keyIndex: 66, lightIndex: 66 },
  { index: 44, label: "C", code: 0x06, x: 4.25, y: 3, w: 1, keyIndex: 67, lightIndex: 67 },
  { index: 45, label: "V", code: 0x19, x: 5.25, y: 3, w: 1, keyIndex: 68, lightIndex: 68 },
  { index: 46, label: "B", code: 0x05, x: 6.25, y: 3, w: 1, keyIndex: 69, lightIndex: 69 },
  { index: 47, label: "N", code: 0x11, x: 7.25, y: 3, w: 1, keyIndex: 70, lightIndex: 70 },
  { index: 48, label: "M", code: 0x10, x: 8.25, y: 3, w: 1, keyIndex: 71, lightIndex: 71 },
  { index: 49, label: ",", code: 0x36, x: 9.25, y: 3, w: 1, keyIndex: 72, lightIndex: 72 },
  { index: 50, label: ".", code: 0x37, x: 10.25, y: 3, w: 1, keyIndex: 73, lightIndex: 73 },
  { index: 51, label: "/", code: 0x38, x: 11.25, y: 3, w: 1, keyIndex: 74, lightIndex: 74 },
  { index: 52, label: "Shift", code: 0xe5, x: 12.25, y: 3, w: 2.75, keyIndex: 75, lightIndex: 75 },
  { index: 53, label: "Ctrl", code: 0xe0, x: 0, y: 4, w: 1.25, keyIndex: 80, lightIndex: 80 },
  { index: 54, label: "Win", code: 0xe3, x: 1.25, y: 4, w: 1.25, keyIndex: 81, lightIndex: 81 },
  { index: 55, label: "Alt", code: 0xe2, x: 2.5, y: 4, w: 1.25, keyIndex: 82, lightIndex: 82 },
  { index: 56, label: "Space", code: 0x2c, x: 3.75, y: 4, w: 6.25, keyIndex: 83, lightIndex: 83 },
  { index: 57, label: "Alt", code: 0xe6, x: 10, y: 4, w: 1.25, keyIndex: 84, lightIndex: 84 },
  { index: 58, label: "Menu", code: 0x65, x: 11.25, y: 4, w: 1.25, keyIndex: 109, lightIndex: 109 },
  { index: 59, label: "Ctrl", code: 0xe4, x: 12.5, y: 4, w: 1.25, keyIndex: 87, lightIndex: 87 },
  { index: 60, label: "Fn", code: 0xff, x: 13.75, y: 4, w: 1.25, keyIndex: 85, lightIndex: 85 },
]

export const KEY_COUNT = RAVEN61_KEYS.length
export const LAYOUT_UNITS = { width: 15, height: 5 }

/** Full travel, in mm. Confirmed on hardware: every key event reports 200 counts. */
export const DEFAULT_TRAVEL_MM = 4.0

export function keyByIndex(index: number): KeyDef | undefined {
  return RAVEN61_KEYS[index]
}

const BY_KEY_INDEX = new Map(RAVEN61_KEYS.map((k) => [k.keyIndex, k]))
const BY_USAGE = new Map(RAVEN61_KEYS.map((k) => [k.code, k]))

/** Maps a firmware key address back to a physical key. */
export function keyByFirmwareIndex(keyIndex: number): KeyDef | undefined {
  return BY_KEY_INDEX.get(keyIndex)
}

/**
 * Maps a HID usage back to a physical key. The firmware addresses keys this way
 * in its analog events and in the stock driver's database, while `keyIndex` is
 * used elsewhere — the two are not interchangeable.
 */
export function keyByUsage(code: number): KeyDef | undefined {
  return BY_USAGE.get(code)
}
